project/admin/views.py
import sys
sys.path.append('../../')

import datetime
from project import db
from datetime import timedelta
from project.users.models import Admin
from project.users.models import Users
from werkzeug.security import check_password_hash
from flask_login import login_required, login_user, logout_user
from flask import Blueprint, redirect, request, render_template, url_for


admins_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admins_blueprint.route('/acceptme-portal', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        username = request.form['admin_email']
        admin_password = request.form['admin_password']
        admin = Admin.query.filter_by(username=username).first()

        if admin:
            if check_password_hash(admin.password, admin_password):
                login_user(admin)
                return redirect(url_for('admin.account'))
            else:
                return render_template('admin/login.html', errors='Incorrect Password')
        return render_template('admin/login.html', errors='Admin does not exist')

    elif request.method == 'GET':
        return render_template('admin/login.html')


@admins_blueprint.route('/admin-account', methods=['GET','POST'])
@login_required
def account():
    try:
        if request.method == 'POST':
            subscription = request.form["subscriptions"]
            username = request.form["username"]

            if subscription == "None":
                obj = Users.query.all()
                return render_template('admin/account.html', users=obj, errors="Please enter a valid subscription value")

            user = Users.query.filter_by(insta_username=username).first_or_404()
            user.subscription_plan = subscription
            user.from_date = datetime.datetime.now()
            user.till_date = datetime.datetime.now() + timedelta(days=int(subscription))
            user.is_subscribed = True
            db.session.commit()

        obj = Users.query.all()
        return render_template('admin/account.html', users=obj, is_admin=True)

    except:
        if request.method == 'POST':
            insta_username = request.form["search"]
            users = Users.query.filter(Users.insta_username.like("%{}%".format(insta_username))).all()
            return render_template('admin/account.html', users=users, is_admin=True)

        obj = Users.query.all()
        return render_template('admin/account.html', users=obj, is_admin=True)



@login_required
@admins_blueprint.route('/admin_logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

project/core/views.py
import datetime
from project import app, bot
from project.users.models import Users
from project.users.memcache_ctrl import client
from project.users.memcache_ctrl import CONSTANT
from common_utilities.login_mappings import mappings
from common_utilities.subscription import check_subscription
from flask_login import login_user, current_user, logout_user
from flask import render_template, Blueprint, request, url_for, redirect, session


core_blueprint = Blueprint('core', __name__, template_folder='templates', static_folder='static')


@core_blueprint.route('/test')
def test():
    return render_template('test.html')

@core_blueprint.route('/', methods=['GET','POST'])
def index():
    if request.method == "POST":
        instagram_username = request.form['userEmailID']
        instagram_password = request.form['userLoginPassword']
        instagram_username = instagram_username.lower()
        session["username"] = {}
        session["username"]["singleton"] = True
        session["username"]["username"] = instagram_username
        session["counter_id"] = instagram_username + CONSTANT.ALL_INFO.value

        is_subscription_check = check_subscription(instagram_username)
        if not is_subscription_check:
            session["message"] = "Please subscribe to login"
            return redirect(url_for('core.pricing'))

        bot_obj = bot()
        resp = bot_obj.login(username=instagram_username, password=instagram_password, ask_for_code=True)
        cl_obj = client.get(instagram_username)

        print(resp)

        if cl_obj.get("bot_obj"):
            client.set(instagram_username, cl_obj)
        else:
            cl_obj["bot_obj"] = bot_obj
            client.set(instagram_username, cl_obj)

        if resp == "906":
            return redirect(url_for('core.verify_code'))

        if resp != True:
            return render_template("index.html", page="index", errors=mappings[resp], **default_args)
        else:
            user = Users.query.filter_by(insta_username=instagram_username).first()
            login_user(user=user)
            print(user.is_authenticated())
            return redirect(url_for('users.accept'))

    elif request.method == "GET":
        try:
            if current_user.is_authenticated:
                instagram_username = current_user.insta_username
                client.delete(instagram_username)
                session.clear()
                logout_user()
            client.delete(current_user)
            session.clear()
        except:
            pass
        return render_template('index.html', page="index", errors=[], **default_args, current_user=current_user)


@core_blueprint.route('/verify-code', methods=["GET", "POST"])
def verify_code():
    if request.method == "POST":
        code = request.form['userLoginPassword']
        instagram_username = session["username"]["username"]

        cl_obj = client.get(instagram_username)
        api_obj = cl_obj["api"]

        resp = api_obj.two_factor_auth_remodified(code, api_obj)


        if resp:
            import time
            api_obj.is_logged_in = True
            api_obj.last_login = time.time()
            client.set(instagram_username, cl_obj)
            resp2 = api_obj.login_flow(True)

            if resp2:
                user = Users.query.filter_by(insta_username=instagram_username).first()
                login_user(user=user)
                return redirect(url_for('users.accept'))
            else:
                print("here")
                return redirect(url_for('core.index'))
                # return render_template("index.html", page="index", errors="Wrong Code", **default_args)
        else:
            print("here1")
            return redirect(url_for('core.index'))
            # return render_template("index.html", page="index", errors="Wrong Code", **default_args)


    elif request.method == "GET":
        return render_template('verify_code.html')


@core_blueprint.route('/pricing')
def pricing():
    return render_template('Pricing.html', **default_args)


@core_blueprint.route('/faq')
def faq():
    return render_template('faq.html', **default_args)


@core_blueprint.route('/contact')
def contact():
    return render_template('Contact.html', **default_args)


@core_blueprint.route('/about')
def about():
    return render_template('about.html', **default_args)


default_args = {}
footer_var = {"cp_year":datetime.datetime.now().year}
@app.before_first_request
def load_default():
    default_args["footer_content"] = render_template("footer.html", **footer_var)
    return default_args

project/users/views.py
import sys
import datetime
from project import app
from common_utilities import Constant
from project.users.models import Counter, Users
from flask_login import login_required, logout_user, current_user
from flask import Blueprint, render_template, session, make_response, jsonify, request, redirect, url_for

sys.path.append('../../')
from project.users.memcache_ctrl import client, CONSTANT


users_blueprint = Blueprint('users', __name__, template_folder='templates')

@users_blueprint.route('/request_accepted_counter', methods=['GET', 'POST'])
@login_required
def request_accepted_counter():
    if request.method == "POST":
        instagram_username = session.get("username").get("username")
        counter_id = session.get("current_counter_id")
        if counter_id is None:
            counter_id_obj = Counter().get_last_counter_info(instagram_username)
            if counter_id_obj is not None:
                counter_id = counter_id_obj.id
                session["current_counter_id"] = counter_id_obj.id
                session.modified = True

        total_success_request, total_request, failed_request = 0, 0, 0
        is_complete = False
        last_date_time = None
        try:
            dict_index_name = instagram_username.lower() + Constant.CONSTANT().ALL_INFO
            all_info = client.get(dict_index_name)
            if isinstance(all_info, dict):
                total_request = all_info[Constant.CONSTANT().TOTAL_REQUEST_TO_BE_ACCEPT]
                total_success_request = all_info[Constant.CONSTANT().SUCCESSFUL_ACCEPTED]
                failed_request = all_info[Constant.CONSTANT().REQUEST_FAILED]
                is_complete = all_info[Constant.CONSTANT().IS_REQUEST_COMPLETE]
                if is_complete == True:
                    last_date_time = all_info.get("update_date")
            else:
                counter_stats_row = Counter.get_one_counter(counter_id)
                if counter_stats_row is not None:
                    total_success_request = counter_stats_row.total_accepted_request
                    total_request = counter_stats_row.input_request_count
                    failed_request = counter_stats_row.input_request_count
                    is_complete = counter_stats_row.is_request_complete
                    last_date_time = counter_stats_row.update_date

        except Exception as error:
            print("Not able to get count ", error)

        response_dict = {"successful": total_success_request,
                         "username": instagram_username.upper(),
                         "failed": failed_request,
                         "isComplete": is_complete,
                         "total": total_request,
                         "lastDateTime": last_date_time.strftime("%a %B %d %Y %I:%M:%S %p") if last_date_time is not None else None}
        return make_response(jsonify(response_dict), 200)


@users_blueprint.route('/accept_pending_requests', methods=["GET", "POST"])
@login_required
def accept():
    if request.method == "POST":
        instagram_username = session["username"]["username"]
        bot_obj = client.get(instagram_username)["bot_obj"]
        no_to_accept = request.form.get("customUserInputNumber", 0)

        init_dict_items = {
            Constant.CONSTANT().TOTAL_REQUEST_TO_BE_ACCEPT: no_to_accept,
            Constant.CONSTANT().IS_REQUEST_COMPLETE: False,
            Constant.CONSTANT().SUCCESSFUL_ACCEPTED: 0,
            Constant.CONSTANT().REQUEST_FAILED: 0,
        }

        dict_get_index = instagram_username.lower() + Constant.CONSTANT().ALL_INFO

        client.set(dict_get_index, init_dict_items)
        new_user_count_req = Counter(
            insta_username=instagram_username,
            input_request_count=no_to_accept,
            total_accepted_request=0,
            total_failed_request=0
        )
        new_user_count_req.save()

        counter_id = new_user_count_req.id
        session["current_counter_id"] = counter_id
        session.modified = True

        ctr_item = Counter.get_one_counter(session["current_counter_id"])
        resp = bot_obj.approve_pending_follow_requests(number_of_requests=int(no_to_accept), ctr_item=ctr_item, init_dict_items=init_dict_items, dict_get_index=dict_get_index, counter_ctr=0)

        if resp == "No request to accept":
            return "No request to accept"

        if resp == None:
            return "True"
        return "True"

    elif request.method == "GET":
        instagram_username = session.get("username").get("username")
        user_obj = Users.query.filter_by(insta_username=instagram_username).first()
        last_day = str(days_between(user_obj.till_date)) + " days"
        return render_template("AcceptRequests.html", last_day=last_day)


@users_blueprint.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    try:
        instagram_username = current_user.insta_username
        if current_user.is_authenticated():
            client.delete(instagram_username)
            session.clear()
        logout_user()
        client.delete(instagram_username)
        session.clear()
    except:
        pass
    return redirect(url_for('core.index'))

def days_between(d1):
    d1 = datetime.datetime.strptime(str(d1.date()), "%Y-%m-%d")
    d2 = datetime.datetime.strptime(str(datetime.datetime.utcnow().date()), "%Y-%m-%d")
    return abs((d2 - d1).days)


default_args = {}
footer_var = {"cp_year": datetime.datetime.now().year}


@app.before_first_request
def load_default():
    default_args["footer_content"] = render_template("footer.html", **footer_var)
    return default_args

project/templates/Contact.html
<!doctype html>
<html lang="en">
<!-- Designed & Developed by G Rohit
https://about.me/grohit -->

<head>
    <title>Contact | AcceptMe | Instagram Requests Acceptor </title>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://i.postimg.cc/B6kk4MyD/AM-icon.png" />
    <meta name="application-name" content="Contact | AcceptMe | Instagram Requests Acceptor">
    <meta name="description"
        content="Contact us for any issues using our application -  AcceptMe. " />
    <meta property="og:description"
        content="Contact us for any issues using our application -  AcceptMe. " />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="keywords"
        content="Pending,request,instagram,insta,gram,telegram,facebook,gmail,whatsapp,intasgrm,graminsta,user,followers,acceptall,allow,users, pending instagram requests, downloader, insta DP, instagram profile pic, instagram profile, picture, download instagram video, video downloader, Acceptme,Accept,Me">
    <meta name="robots" content="index, follow">
    <meta name="copyright" content="Acceptme.in">

    <!-- bootsrap -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- font awesome -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
        integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- custom css -->

    <link rel="stylesheet" href="{{ url_for('static', filename = 'acceptmestyling.css') }}">
</head>

<body>

    <!-- Navbar STARTS -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-fixed-top">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">
            <img src="https://i.postimg.cc/5NWT002Q/Accept-ME-white.png" alt="accept me logo" width="120px"
                height="auto">
        </a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse mobileMenubg" id="navbarCollapse">
            <ul class="navbar-nav ml-auto text-white text-center ">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.index') }}">Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.about') }}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.pricing') }}">Pricing</a>
                </li>
                <li class="nav-item" id="activePage">
                    <a class="nav-link" href="{{ url_for('core.faq') }}">FAQ <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.contact') }}">Contact</a>
                </li>
                {% if current_user.is_authenticated and not is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
                </li>
                {% endif %}
                {% if current_user.is_authenticated and is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.logout') }}">Admin LogOut</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Navbar ENDS -->

    <!-- main content STARTS -->

     
    <section class="pt-5 pb-5">
        <div class="container">
            <div class="row">
                <div class="col p-4 text-center m-auto">
                    <h2 class="text-white title">
                        Got a question about using AcceptMe?</h2>
                    <p class="text-white">
                        Kindly ensure you have gone thru <a href="{{ url_for('core.faq') }}" class="btn-link text-white" target="_blank">FAQ page <i class="fas fa-chevron-circle-right"></i></a> and If you still have any queries, feel free to reach out to us.
                    </p>
                </div>
            </div>

            <div class="row ">
                <div class="col-sm-12 col-xs-12 col-md-6 col-lg-6 text-center m-auto">
 
                        <div class="card contact-card animated flip slow bg-warning">
                            <h3 class="card-header text-uppercase font-weight-bold">Contact us</h3>
                            <div class="p-3">
                                <img src="https://i.postimg.cc/R0jDFbP6/rick-and-morty-transparent-background-2.png"
                                     alt="contact-us-image" class="img-fluid rounded  w-75">
                            </div>
                            <div class="card-body">
                                <h2 class="card-title "></h2>
                                <p class="card-text lead font-weight-bold">Reach out to us for any issues with <br> Pricing, Subscription or any technical issues. 
                                 </p>

                                 <div>
                                 
                                 <a href="https://api.whatsapp.com/send?phone=917014716530&text=Hi%20there,%20I%20have%20sent%20you%20the%20payment%20and%20here%20is%20the%20screenshot:%20"
                                target="_blank" class="btn btn-success btn"> <i class="fab fa-whatsapp    "></i> Contact us on Whatsapp </a>

                                </div>
                            </div>
                            <div class="card-footer">
                                <ul class="list-unstyled text-dark small">
                                    <li> App Owned by Arham Surana and Taresh Goyal
                                    </li>
                                    <li> Designed and developed by <a href="https://grohit.com/" class="text-dark" target="_blank">G Rohit</a>
                                    <li>Backend Development and Deployment done by: <a href="https://patelfarhaan.github.io/" class="text-dark" target="_blank">Farhaan Patel</a></li>
                                </ul>
                            </div>
                        </div>
                 
                </div>
            </div>
        </div>
    </section>


    <!-- main content ENDS -->

    <div class="push"></div>
</body>

<!-- Foooter starts -->

{{ footer_content|safe }}

<!-- Foooter ENDS -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

<script>
    $(function () {
        $(document).scroll(function () {
            var $nav = $(".navbar-fixed-top");
            $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        });
    });
</script>

<script src="{{ url_for('static', filename = 'main.js') }}"></script>

</html>

project/templates/Pricing.html
<!doctype html>
<html lang="en">
<!-- Designed & Developed by G Rohit
https://about.me/grohit -->

<head>
    <title>Pricing  | AcceptMe | Instagram Requests Acceptor </title>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://i.postimg.cc/B6kk4MyD/AM-icon.png" />
    <meta name="application-name" content="Pricing | AcceptMe | Instagram Requests Acceptor">
    <meta name="description"
        content="Learn about economical subscription plans of AcceptMe - An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
    <meta property="og:description"
        content="Learn about economical subscription plans of AcceptMe - An efficient website to help you accept all your pending requests on Instagram profile in a very convenient way. Visit once and experience the magic." />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="keywords"
        content="Pending,request,instagram,insta,gram,telegram,facebook,gmail,whatsapp,intasgrm,graminsta,user,followers,acceptall,allow,users, pending instagram requests, downloader, insta DP, instagram profile pic, instagram profile, picture, download instagram video, video downloader, Acceptme,Accept,Me">
    <meta name="robots" content="index, follow">
    <meta name="copyright" content="Acceptme.in">

    <!-- bootsrap -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- font awesome -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
        integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- custom css -->

    <link rel="stylesheet" href="{{ url_for('static', filename = 'acceptmestyling.css') }}">
</head>

<body>

    <!-- Navbar STARTS -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-fixed-top">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">
            <img src="https://i.postimg.cc/5NWT002Q/Accept-ME-white.png" alt="accept me logo" width="120px"
                height="auto">
        </a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse mobileMenubg" id="navbarCollapse">
            <ul class="navbar-nav ml-auto text-white text-center ">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.index') }}">Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.about') }}">About</a>
                </li>
                <li class="nav-item" id="activePage">
                    <a class="nav-link" href="{{ url_for('core.pricing') }}">Pricing <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link" href="{{ url_for('core.faq') }}">FAQ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.contact') }}">Contact</a>
                </li>
                {% if current_user.is_authenticated and not is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
                </li>
                {% endif %}
                {% if current_user.is_authenticated and is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.logout') }}">Admin LogOut</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Navbar ENDS -->

    <!-- main content STARTS -->

    <section class="pricing">
        <div class="container">
            <div class="row mt-5" id="pricing-page-top">
                <div class="col-md-12 text-center">
                    <h1 class="text-white animated bounceInDown slow display-2  ">Pricing </h1>
                    <p class="animated pulse infinite slow delay-5s text-white mb-4">
                        <a href="https://api.whatsapp.com/send?phone=917014716530&text=Hi%20there,%20I%20have%20sent%20you%20the%20payment%20and%20here%20is%20the%20screenshot:%20"
                        target="_blank" class="btn btn-success btn"> <i class="fab fa-whatsapp    "></i>
                        Verify your Payment</a>
                    </p>
                    <div class="card-deck">
                        <div class="card bg-black animated slideInUp slow">
                            <h3 class="card-header">For Single Account</h3>
                            <div class="card-body">
                                <h2 class="card-title"><i class="fas fa-rupee-sign"></i>400 Only</h2>
                                <h4 class="card-text">Unlimited accepts</h4>
                                <p class="card-text font-text">Validity: 15 (Fifteen) Days</p>
                            </div>
                            <div class="card-footer">
                                <p class="p-2">
                                    Click on:
                                </p>
    <p>
        <a href="https://kutt.it/am400" class="btn btn-action mt-3" target="_blank">Pay via
            InstaMojo</a>
    </p>
                                <!-- <p class="badge bg-secondary p-2 rounded shadow-lg">
                                    Or scan: <br> <br> <img src="https://i.postimg.cc/tCRk5GwN/am400.png" alt="am400"
                                                            class="img-fluid" title="open your camera/QR code app and scan me">
                                </p> -->
                            </div>
                        </div>
                        <div class="card bg-black animated slideInUp slow">
                            <h3 class="card-header  ">For Single Account</h3>
                            <div class="card-body">
                                <h2 class="card-title  "><span style="text-decoration: none"><i class="fas fa-rupee-sign"></i>600 Only</span>
                                </h2>
                                <h4 class="card-text  ">Unlimited accepts</h4>
                                <p class="card-text font-text">Validity: 30 (Thirty) Days</p>
                            </div>
                            <div class="card-footer">
                                <p class="p-2">
                                    Click on:  
                                </p>
                                <p>
                                    <a href="https://kutt.it/am600" class="btn btn-action mt-3" target="_blank">Pay via
                                        InstaMojo</a>
                                </p>
                                <!-- <p class="badge bg-secondary p-2 rounded shadow-lg">
                                    Or scan: <br> <br> <img src="https://i.postimg.cc/BZBNHnYv/am600.png" alt="am600"
                                                            class="img-fluid" title="open your camera/QR code app and scan me">
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-12 text-center">
                    <p class="text-white text-center">For subscriptions of multiple account, kindly drop an email to us
                        at <a href="mailto:Acceptmeinfo@gmail.com"
                              class="font-weight-bold text-warning">Acceptmeinfo@gmail.com</a></p>
                </div>
            </div>
        </div>
      </section>

    <!-- main content ENDS -->
 {% if session["message"] %}
    <div class="bg-white text-center">
        <p class="text-danger p-2 ">{{ session["message"] }}</p>
    </div>
{% endif %}

    <div class="push"></div>
</body>

<!-- Foooter starts -->

{{ footer_content|safe }}

<!-- Foooter ENDS -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

<script>
    $(function () {
        $(document).scroll(function () {
            var $nav = $(".navbar-fixed-top");
            $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
        });
    });
</script>

<script src="{{ url_for('static', filename = 'main.js') }}"></script>

</html>

project/templates/code.html
{% extends "index.html" %}
{% block content %}
    <form method="POST" class="text-center"
          name="loginForm" autocomplete="off">
        <br>
        <br>
        <h1>Please select where do you want to receive your verification code?</h1>
        <input type="submit" name="action" value="email" class="loginBtn"><br><br>
        <input type="submit" name="action" value="phone" class="loginBtn"> <br><br>
    </form>

{% endblock %}

project/templates/footer.html
<footer>
    <div>
        <a href="{{ url_for('core.index') }}">AcceptMe</a> &copy; <span id="currentYear">{{cp_year}}</span>
    </div>
</footer>